# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Urban Colab Architecture
email: info@urbancolab.design
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: https://twitter.com/kurtneiswender
github_username: https://github.com/kurtneiswender
minimal_mistakes_skin: dark
search: true
#logo: "/assets/images/2023 Logo.jpg"
# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# Outputting
permalink: /:categories/:title/
paginate: 4 # amount of posts to show
paginate_path: /page:num/
timezone: America/Detroit
repository: "kurtneiswender/kurtneiswender"

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme


author:
  name   : "Kurt Neiswender, AIA"
  avatar : "/assets/images/2023 Logo.jpg"
  bio    : "Urban Colab Architecture intends for all projects to be considerate of the ecological impact of their designed solution. Urban Colab Architecture provides solutions that are architectural in nature Urban Colab Architecture intends for all projects to be considerate of the ecological impact of their designed solution."
  links:
    - label: "Podcast"
      icon: "fas fa-fw fa-podcast"
      url: "https://coffeesketchpodcast.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/kurtneiswender"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kurtneiswender"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"
    - label: "Twitch"
      icon: "fab fa-fw fa-twitch"
      url: "https://www.twitch.tv/coffeesketchpodcast"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/kurtneiswender"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kurtneiswender"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/urbancolabarchitecture"
    - label: "Twitch"
      icon: "fab fa-fw fa-twitch"
      url: "https://www.twitch.tv/coffeesketchpodcast"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

  # _portfolio
  - scope:
      path: "_portfolio"
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections: 
  portfolio: 
    output: true
    permalink: /:collection/:path/
